# Generated by Django 3.0.6 on 2020-05-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platform',
            new_name='platform_group',
        ),
        migrations.AddField(
            model_name='platform',
            name='tenant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='tenancy.Tenant'),
            preserve_default=False,
        ),
    ]
