# Generated by Django 3.0.6 on 2020-08-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operator_contact_person',
            field=models.TextField(blank=True, help_text='A primary contact person on the operator tenant', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='owner_contact_person',
            field=models.TextField(blank=True, help_text='A primary contact person on the owner tenant', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='External'),
        ),
    ]
