# Generated by Django 3.0.6 on 2020-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200807_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('RELATED', 'Is related to'), ('DEPENDS_ON', 'Depends on'), ('BELONGS_TO', 'Belongs to')], max_length=20)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='services.Service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='services.Service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='relations',
            field=models.ManyToManyField(through='services.ServiceRelation', to='services.Service'),
        ),
    ]
