# Generated by Django 3.0.6 on 2020-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200807_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerelation',
            name='comment',
            field=models.CharField(blank=True, help_text='A comment about the relation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerelation',
            name='relation',
            field=models.CharField(choices=[('RELATED', 'Is related to'), ('DEPENDS_ON', 'Depends on'), ('BELONGS_TO', 'Belongs to'), ('DUPLICATES', 'Duplicates')], max_length=20),
        ),
    ]
