# Generated by Django 3.0.6 on 2020-08-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200807_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='links', to='services.Service'),
        ),
    ]
