# Generated by Django 3.0.6 on 2020-08-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20200807_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='business_overview',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hours_of_operation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='relations',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_level',
        ),
        migrations.RemoveField(
            model_name='service',
            name='technical_overview',
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, help_text='A short summary about the service', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='services.Service'),
        ),
        migrations.AlterField(
            model_name='servicerelation',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_service_set', to='services.Service'),
        ),
        migrations.AlterField(
            model_name='servicerelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_service_set', to='services.Service'),
        ),
    ]
