@startuml


Class Service
Class Tenant
Class TenantGroup
Class Environment
Class Platform
Class PlatformGroup

Tenant "0..1" --* "*" TenantGroup
TenantGroup "1" *-- "*" TenantGroup : contains

Platform "*" -- "1" Tenant : owns
Platform "0..1" -- PlatformGroup
PlatformGroup "1" -- "*" PlatformGroup: contains

Tenant -- Service : owns

Service "1" *-- "*"  Service : depends_on

Service "0..*" -- "1" Platform
Service "1" -- "1..*" Environment

@enduml--